api_platform:
    title: Hello API Platform
    version: 1.0.0
    collection:
        pagination:
            enabled: true
            client_items_per_page: true
            items_per_page: 30
    mapping:
        paths: 
            - '%kernel.project_dir%/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources'
            - '%kernel.project_dir%/config/api_platform'
            - '%kernel.project_dir%/src/Entity'
    # formats:
        # json:
        # mime_types: ['application/json']
        # jsonld:
        #     mime_types: ['application/ld+json']
        # html:
        #     mime_types: ['text/html']
        # multipart:
        #     mime_types: ['multipart/form-data']
    patch_formats:
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    # keep_legacy_inflector: false
    # use_symfony_listeners: true