services:
    php:
        image: ghcr.io/sylius/sylius-php:8.2-alpine
        environment:
          - APP_ENV=dev
          - APP_DEBUG=1
          - APP_SECRET=EDITME
          - DATABASE_URL=mysql://open_marketplace:${MYSQL_PASSWORD:-nopassword}@mysql/open_marketplace
          - MAILER_URL=smtp://mailhog:1025
          - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
    # sylius:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - "8000:80"
    #     volumes:
    #         - .:/var/www/sylius
    #     depends_on:
    #         - mysql
    mysql:
        image: mysql:8.0
        platform: linux/amd64
        healthcheck:
            test: '/usr/bin/mysql --execute "SHOW databases;"'
            timeout: 3s
            interval: 1s
            retries: 10
        environment:
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
              - MYSQL_DATABASE=open_marketplace
              - MYSQL_USER=open_marketplace
              - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
        cap_add:
            - SYS_NICE # prevent "mbind: Operation not permitted" errors
        volumes:
            - mysql-data:/var/lib/mysql:rw
        ports:
            - "3307:3306"
    nginx:
        image: ghcr.io/sylius/sylius-nginx:latest
    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest

volumes:
  mysql-data:
  public-media:
  fixture-images:
